# Generated by Django 6.0 on 2025-12-04 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator', models.CharField(blank=True, max_length=150, null=True)),
                ('room_name', models.CharField(max_length=255)),
                ('one_time', models.BooleanField(default=True)),
                ('allowed_count', models.IntegerField(default=2)),
                ('issued_count', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_issued_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='chat.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
