# Generated by Django 6.0 on 2025-12-08 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_session_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('joined', 'Joined room'), ('left', 'Left room'), ('meeting_started', 'Meeting started'), ('meeting_ended', 'Meeting ended'), ('screen_share_started', 'Screen share started'), ('screen_share_stopped', 'Screen share stopped')], max_length=64)),
                ('identity', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.meetinglink')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_events', to='chat.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
