# Generated by Django 6.0 on 2025-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_meetingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinglink',
            name='allowed_count',
        ),
        migrations.RemoveField(
            model_name='meetinglink',
            name='issued_count',
        ),
        migrations.RemoveField(
            model_name='meetinglink',
            name='last_issued_at',
        ),
        migrations.RemoveField(
            model_name='meetinglink',
            name='one_time',
        ),
        migrations.RemoveField(
            model_name='meetinglink',
            name='used',
        ),
        migrations.AddField(
            model_name='meetinglink',
            name='room_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
